### ISSUE TITLE
ValueError thrown on configuration if password contains a percent "%" symbol

### ISSUE THREAD

**Issue by philMarius** [databricks/databricks-cli#277]
Steps to replicate:

- `pip install databricks-cli`
- Run `databricks configure` in the terminal
- Enter Host and Username correctly
- Input password containing a percentage "%" symbol

Error thrown below is for a password of just "%":

```
Traceback (most recent call last):
  File "/home/user/miniconda3/bin/databricks", line 8, in <module>
    sys.exit(cli())
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/miniconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/miniconda3/lib/python3.7/site-packages/databricks_cli/configure/cli.py", line 78, in configure_cli
    _configure_cli_password(profile, insecure_str)
  File "/home/user/miniconda3/lib/python3.7/site-packages/databricks_cli/configure/cli.py", line 60, in _configure_cli_password
    update_and_persist_config(profile, new_config)
  File "/home/user/miniconda3/lib/python3.7/site-packages/databricks_cli/configure/provider.py", line 97, in update_and_persist_config
    _set_option(raw_config, profile, PASSWORD, databricks_config.password)
  File "/home/user/miniconda3/lib/python3.7/site-packages/databricks_cli/configure/provider.py", line 73, in _set_option
    raw_config.set(profile, option, value)
  File "/home/user/miniconda3/lib/python3.7/configparser.py", line 1198, in set
    super().set(section, option, value)
  File "/home/user/miniconda3/lib/python3.7/configparser.py", line 893, in set
    value)
  File "/home/user/miniconda3/lib/python3.7/configparser.py", line 402, in before_set
    "position %d" % (value, tmp_value.find('%')))
ValueError: invalid interpolation syntax in '%' at position 0
```

**Comment by philMarius** [comment]
Related to #103

**Comment by philMarius** [comment]
Any update on this?

**Comment by ncoish** [comment]
This issue is also occurring for me on version 0.13.0, Python 3.8.5

**Comment by gradientjanitor** [comment]
occurring for me as well.

**Comment by chrisst** [comment]
**This repository has been archived.**

The legacy `databricks/databricks-cli` is deprecated and has been fully replaced by the new Databricks CLI at **https://github.com/databricks/cli**.

We are closing all open issues here as part of archiving this repository. If your issue still affects the new CLI, we'd appreciate you re-opening it at https://github.com/databricks/cli/issues so the team can track and address it there.
