### ISSUE TITLE
Python 3.8 TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by ddska** [databricks/databricks-cli#301]
I installed databricks-cli 0.11.0 via `pip install databricks-cli` on my Ubuntu 20.04 with Python 3.8.2.

Configured it without any errors via `databricks configure --token`.

Now, when I run `databricks fs ls -l "dbfs:/"` I get the following output:

`Error: TypeError: an integer is required (got type bytes)`

**Comment by ddska** [comment]
Installation log:

```
pip install databricks-cli 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Collecting databricks-cli
  Downloading databricks-cli-0.11.0.tar.gz (49 kB)
     |████████████████████████████████| 49 kB 1.2 MB/s 
Requirement already satisfied: click>=6.7 in ./.local/lib/python3.8/site-packages (from databricks-cli) (7.1.2)
Requirement already satisfied: requests>=2.17.3 in /usr/lib/python3/dist-packages (from databricks-cli) (2.22.0)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from databricks-cli) (1.14.0)
Collecting tabulate>=0.7.7
  Downloading tabulate-0.8.7-py3-none-any.whl (24 kB)
Building wheels for collected packages: databricks-cli
  Building wheel for databricks-cli (setup.py) ... done
  Created wheel for databricks-cli: filename=databricks_cli-0.11.0-py3-none-any.whl size=90300 sha256=493f2d198b53404efc1a80774f851b82eb26ac5aec6434e153749377dbe61102
  Stored in directory: /home/user/.cache/pip/wheels/b9/f6/7e/6a96e9345afe0a27903541766afe0f6229900bbcd33b096032
Successfully built databricks-cli
Installing collected packages: tabulate, databricks-cli
Successfully installed databricks-cli-0.11.0 tabulate-0.8.7
```

**Comment by bogdanghita-db** [comment]
Could you provide the exception stack trace? Also, is this happening for `fs ls` only? Do other `fs` operations succeed?

**Comment by ddska** [comment]
I don't know how to get exception stack trace. `--debug` option adds only one line to output:

```HTTP debugging enabled```

Command `databricks fs cp file.csv "dbfs:/"` also gives the same error.

**Comment by bogdanghita-db** [comment]
I could not reproduce the issue. Does it happen only for `databricks fs` commands or for others too (e.g. `jobs`, `secrets`, etc.)?

**Comment by shubhamInfoWorks** [comment]
Use python 3.7, It will work, had the same problem, with python 3.8, it gives error.

**Comment by alexott** [comment]
@bogdanghita-db the issue is reproduced if you have Python 3.8 & pyspark 2.4.x installed (works fine with 3.0.x):

```
Traceback (most recent call last):
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/utils.py", line 43, in decorator
    return function(*args, **kwargs)
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/configure/config.py", line 50, in decorator
    config = get_config()
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/configure/provider.py", line 119, in get_config
    config = DefaultConfigProvider().get_config()
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/configure/provider.py", line 198, in get_config
    config = provider.get_config()
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/configure/provider.py", line 222, in get_config
    context = self._get_spark_task_context_or_none()
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/databricks_cli/configure/provider.py", line 210, in _get_spark_task_context_or_none
    from pyspark import TaskContext  # pylint: disable=import-error
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/serializers.py", line 72, in <module>
    from pyspark import cloudpickle
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/Users/alexey.ott/opt/anaconda3/lib/python3.8/site-packages/pyspark-2.4.7-py3.8.egg/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
Error: TypeError: an integer is required (got type bytes)
```

**Comment by markddavidoff** [comment]
It seems this library does not support 3.8+ it should be updated to reflect that. This error is a common symptom of lack of
 python 3.8+ support

**Comment by markddavidoff** [comment]
actually specifically I can reproduce this without pyspark, just stock `databricks-cli==0.15.0` running many commands, one being `databricks tokens list` or `databricks jobs list`

**Comment by markddavidoff** [comment]
Ya'll, the `eat_exceptions` makes it annoying to get any stack trace, even in "debug" mode. If you look at the code when it is NOT in debug mode, it just silences exceptions 😠 . I'll open a pr to address that if i get a chance however, back to this issue:

Here is a stack trace @bogdanghita-db :
```
Traceback (most recent call last):
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/utils.py", line 44, in decorator
    return function(*args, **kwargs)
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/configure/config.py", line 50, in decorator
    config = get_config()
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/configure/provider.py", line 119, in get_config
    config = DefaultConfigProvider().get_config()
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/configure/provider.py", line 198, in get_config
    config = provider.get_config()
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/configure/provider.py", line 222, in get_config
    context = self._get_spark_task_context_or_none()
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/databricks_cli/configure/provider.py", line 210, in _get_spark_task_context_or_none
    from pyspark import TaskContext  # pylint: disable=import-error
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/__init__.py", line 51, in <module>
    from pyspark.context import SparkContext
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/context.py", line 31, in <module>
    from pyspark import accumulators
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/accumulators.py", line 97, in <module>
    from pyspark.serializers import read_int, PickleSerializer
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/serializers.py", line 74, in <module>
    from pyspark import cloudpickle
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/cloudpickle.py", line 145, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/Users/mark.davidoff/.virtualenvs/traffic-attribution/lib/python3.9/site-packages/pyspark/cloudpickle.py", line 126, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)

```
 
 What is weird is that i don't have pyspark installed! (not in my pip freeze!)

**Comment by markddavidoff** [comment]
actually, i somehow do? but it is not in my virtual env 🤔 . I oddly cannot find how or why `pyspark` is installed as it is not in pip freeze but I see it in the site packages in my virtual env..... wut?

Anyway, following this stack post:
https://stackoverflow.com/questions/58700384/how-to-fix-typeerror-an-integer-is-required-got-type-bytes-error-when-tryin
here is a work around:
```
pip install --upgrade pyspark
```
to upgrade your pyspark to a version that supports Python 3.8+. However this may not suitable for anyone using a strict package version manager like `Poetry`

**Comment by markddavidoff** [comment]
ah i see, pulling debug off of the click context object means that these all have different behaviors, where debugging was only enabled in the correct place in one of these
```
databricks --debug jobs list
```
vs
```
databricks  jobs --debug list
```
vs
```
databricks  jobs  list --debug
```
enable debug only at there specific layers. For all of them you need
```
databricks --debug  jobs -debug list --debug
```
😠
