### ISSUE TITLE
Databricks CLI - ImportError: cannot import name 'Iterable' from 'collections'

### ISSUE THREAD

**Issue by BenResTech** [databricks/databricks-cli#406]
Using Databricks CLI 0.16.2 with Python3.10 I get the following error:
```
❯ ~/.local/bin/databricks configure --token
Traceback (most recent call last):
  File "/home/ben/.local/bin/databricks", line 5, in <module>
    from databricks_cli.cli import cli
  File "/home/ben/.local/lib/python3.10/site-packages/databricks_cli/cli.py", line 31, in <module>
    from databricks_cli.dbfs.cli import dbfs_group
  File "/home/ben/.local/lib/python3.10/site-packages/databricks_cli/dbfs/cli.py", line 25, in <module>
    from tabulate import tabulate
  File "/usr/lib/python3/dist-packages/tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

It appears that this has [moved to `collections.abc` from `collections`](https://docs.python.org/3/library/collections.abc.html) in Python3.10.

**Comment by chrisst** [comment]
**This repository has been archived.**

The legacy `databricks/databricks-cli` is deprecated and has been fully replaced by the new Databricks CLI at **https://github.com/databricks/cli**.

We are closing all open issues here as part of archiving this repository. If your issue still affects the new CLI, we'd appreciate you re-opening it at https://github.com/databricks/cli/issues so the team can track and address it there.
