### ISSUE TITLE
Displaying help text for unity-catalog commands on WSL on Windows produces error

### ISSUE THREAD

**Issue by HansjoergW** [databricks/databricks-cli#555]
databricks cli version 0.17.3

When trying to execute `databricks unity-catalog -h` on WSL on windows (Ubuntu-20.04), the following error message appears:
`
Traceback (most recent call last):
  File "/home/u118187/.local/bin/databricks", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1476, in handle_parse_result
    value = invoke_param_callback(
  File "/usr/lib/python3/dist-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/python3/dist-packages/click/core.py", line 860, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/usr/lib/python3/dist-packages/click/core.py", line 516, in get_help
    return self.command.get_help(self)
  File "/usr/lib/python3/dist-packages/click/core.py", line 879, in get_help
    self.format_help(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 898, in format_help
    self.format_options(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1017, in format_options
    self.format_commands(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1082, in format_commands
    formatter.write_dl(rows)
  File "/usr/lib/python3/dist-packages/click/formatting.py", line 203, in write_dl
    self.write(next(lines) + '\n')
`

The error does NOT appear when `databricks unity-catalog -h` is executed in the windows command shell.

**Comment by pietern** [comment]
@HansjoergW Thanks for the report.

Do you see anything above/below the stack trace, e.g. an exception or error message?

The stack trace alone doesn't tell anything about the underlying error.

**Comment by HansjoergW** [comment]
```
u118187@C70C7332:~/test/grouptesttf$ databricks unity-catalog --help
Traceback (most recent call last):
  File "/home/u118187/.local/bin/databricks", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1135, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1089, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1476, in handle_parse_result
    value = invoke_param_callback(
  File "/usr/lib/python3/dist-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/usr/lib/python3/dist-packages/click/core.py", line 860, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/usr/lib/python3/dist-packages/click/core.py", line 516, in get_help
    return self.command.get_help(self)
  File "/usr/lib/python3/dist-packages/click/core.py", line 879, in get_help
    self.format_help(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 898, in format_help
    self.format_options(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1017, in format_options
    self.format_commands(ctx, formatter)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1082, in format_commands
    formatter.write_dl(rows)
  File "/usr/lib/python3/dist-packages/click/formatting.py", line 203, in write_dl
    self.write(next(lines) + '\n')
StopIteration
```
There is only the "StopIteration" at the end, there is nothing upfront the stacktrace.

**Comment by chrisst** [comment]
**This repository has been archived.**

The legacy `databricks/databricks-cli` is deprecated and has been fully replaced by the new Databricks CLI at **https://github.com/databricks/cli**.

We are closing all open issues here as part of archiving this repository. If your issue still affects the new CLI, we'd appreciate you re-opening it at https://github.com/databricks/cli/issues so the team can track and address it there.
