### ISSUE TITLE
Trouble running in AWS codebuild container

### ISSUE THREAD

**Issue by coltonflowers1** [databricks/databricks-cli#556]
I have a docker image from which I build a devcontainer. Within that devcontainer, I set DATABRICKS_HOST and DATABRICKS_ TOKEN, and I am able to succesfully run the following: 

`databricks workspace ls /Users --debug`

However when I use the same command in buildspec.yml for AWS codebuild (passing in the same env vars). that runs on the same image, I run into the following: 
```

HTTP debugging enabled
--
Error: InvalidSchema: No connection adapters were found for '://None/api/2.0/workspace/list'
Traceback (most recent call last):
File "/usr/local/lib/python3.8/site-packages/databricks_cli/utils.py", line 45, in decorator
return function(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/databricks_cli/configure/config.py", line 67, in decorator
return function(*args, **kwargs)
File "/usr/local/lib/python3.8/site-packages/databricks_cli/workspace/cli.py", line 57, in ls_cli
objects = WorkspaceApi(api_client).list_objects(workspace_path)
File "/usr/local/lib/python3.8/site-packages/databricks_cli/workspace/api.py", line 95, in list_objects
response = self.client.list(workspace_path, headers=headers)
File "/usr/local/lib/python3.8/site-packages/databricks_cli/sdk/service.py", line 962, in list
return self.client.perform_query('GET', '/workspace/list', data=_data, headers=headers)
File "/usr/local/lib/python3.8/site-packages/databricks_cli/sdk/api_client.py", line 155, in perform_query
resp = self.session.request(method, self.get_url(path, version=version), params = translated_data,
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 695, in send
adapter = self.get_adapter(url=request.url)
File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 792, in get_adapter
raise InvalidSchema(f"No connection adapters were found for {url!r}")
requests.exceptions.InvalidSchema: No connection adapters were found for '://None/api/2.0/workspace/list'

```

EDIT: databricks-cli=0.17.3

**Comment by coltonflowers1** [comment]
Update: Seems to be a secrets issue? I'm passing the env vars as parameter store parameters. When I set the host explicitly in the buildspec.yml,  I don't get this issue, but I do proceed to get a 403 since it presumably can't read DATABRICKS_TOKEN from the parameter list.

**Comment by pietern** [comment]
Thanks for posting the issue.

W.r.t `'://None/api/2.0/workspace/list'` the host isn't set. Combined with your observation that you get 403s when you manually set the host, it's probably an issue with how these variables are passed through in CodeBuild.

Closing as this is not something we can solve in the CLI.
