### ISSUE TITLE
There is no active click context

### ISSUE THREAD

**Issue by cozos** [databricks/databricks-cli#563]
Following https://docs.databricks.com/dev-tools/python-api.html#examples with `click==7.1.2` and `databricks-cli==0.17.3` and this code:

```py
def main():
    databricks_client = ApiClient(
        host="SOMETHING",
        token="SOMETHING",
    )
    dbfs_api = DbfsApi(databricks_client)
    dbfs_api.cp(
        recursive=False,
        overwrite=True,
        src="/tmp/something.whl",
        dst="dbfs://path/something.whl",
    )
```

I get this error:

```
Traceback (most recent call last):
  File "/home/arwin.tio/my_code.py", line 159, in <module>
    main()
  File "/home/arwin.tio/my_code.py", line 150, in main
    dst="dbfs://path/something.whl",
  File "/home/arwin.tio/my_dirs/databricks_cli/dbfs/api.py", line 270, in cp
    self._copy_to_dbfs_non_recursive(src, DbfsPath(dst), overwrite, headers=headers)
  File "/home/arwin.tio/my_dirs/databricks_cli/dbfs/dbfs_path.py", line 36, in __init__
    self.validate()
  File "/home/arwin.tio/my_dirs/databricks_cli/dbfs/dbfs_path.py", line 53, in validate
    'It must start with dbfs:/').format(repr(self)))
  File "/home/arwin.tio/my_dirs/databricks_cli/utils.py", line 95, in error_and_quit
    ctx = click.get_current_context()
  File "/home/arwin.tio/my_dirs/click/globals.py", line 25, in get_current_context
    raise RuntimeError("There is no active click context.")
RuntimeError: There is no active click context.
```

I understand that the true error is `It must start with dbfs:/`, but it is being obscured by the click error.

**Comment by pietern** [comment]
Thanks for reporting the issue.

The article shows use of the `databricks_cli.*.api` packages. While they may work you can run into issues like the one you describe. It's a stop gap in lieu of a proper Python SDK for our API. Their only (main) purpose is to support the underlying CLI commands and as such we don't test them when used without click.

Please only use `databricks_cli.sdk` as public API if you intend to use this package as a library.
