### ISSUE TITLE
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by JWDobken** [databricks/databricks-cli#586]
A simple script to copy python dependencies to Databricks with python:

```py
api_client = ApiClient(
    host  = os.getenv('DATABRICKS_HOST'),
    token = os.getenv('DATABRICKS_TOKEN')
)
dbfs_api  = DbfsApi(api_client)
        
dbfs_api.cp(
    recursive=True,
    overwrite=True,
    src=f"scripts/requirements.txt",
    dst=f"dbfs:/deployments/scripts/requirements.txt"
)
```

Raises the following error:

```logs
Traceback (most recent call last):
File "/__w/1/s/artifacts.py", line 12, in copy_python_dependencies
dbfs_api.cp(
File "/home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/databricks_cli/dbfs/api.py", line 273, in cp
self._copy_to_dbfs_non_recursive(src, DbfsPath(dst), overwrite, headers=headers)
File "/home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/databricks_cli/dbfs/api.py", line 205, in _copy_to_dbfs_non_recursive
if e.response.json()['error_code'] == DbfsErrorCodes.RESOURCE_DOES_NOT_EXIST:
File "/home/AzDevOps_azpcontainer/.local/lib/python3.9/site-packages/requests/models.py", line 975, in json
raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It runs in the [official Python 3.9 container](https://hub.docker.com/layers/library/python/3.9/images/sha256-2a8698e36f267e998d72fb2a7182a0885c119bfa686995318d7fae5a2e0fa35a?context=explore) with installed [databrick-cli version 0.17.3](https://pypi.org/project/databricks-cli/) (latest at writing)

**Comment by pietern** [comment]
I suspect that the response is not valid JSON.

Could you try double checking that your token is working?

Btw, there may be a typo in your script with `mycontianer`.

**Comment by JWDobken** [comment]
It is a valid token and the host address is correct.

Token is obtained with:

```bash
export DATABRICKS_TOKEN=$(curl -X GET -H 'Content-Type: application/x-www-form-urlencoded' \
      -d "grant_type=client_credentials&client_id=${CLIENT_ID}&resource=${RESOURCE_ID}&client_secret=${CLIENT_SECRET}" \
      https://login.microsoftonline.com/${TENANT_ID}/oauth2/token | python -c "import sys, json; print(json.load(sys.stdin)['access_token'])")
```

**Comment by JWDobken** [comment]
oopsie... the DATABRICKS_HOST was wrong. Maybe return the raw text on `raise_for_status`

**Comment by pietern** [comment]
Thanks for the update. I agree, hiding the original error is not great here...
