### ISSUE TITLE
Unable to start databricks CLI

### ISSUE THREAD

**Issue by kharigardner** [databricks/databricks-cli#593]
Unable to start databricks CLI on a Windows 11 machine with Python 3.10 installed. Any initialization command (databricks, databricks connect, etc.) results in the following error:

``
Traceback (most recent call last):
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\Scripts\databricks.exe\__main__.py", line 4, in <module>
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\site-packages\databricks_cli\cli.py", line 26, in <module>
    from databricks_cli.configure.config import profile_option, debug_option
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\site-packages\databricks_cli\configure\config.py", line 31, in <module>
    from databricks_cli.oauth.oauth import check_and_refresh_access_token
  File "C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\site-packages\databricks_cli\oauth\oauth.py", line 36, in <module>
    from jwt import PyJWTError
ImportError: cannot import name 'PyJWTError' from 'jwt' (C:\Users\khari\AppData\Local\Programs\Python\Python310\lib\site-packages\jwt\__init__.py)

**Comment by chrisst** [comment]
**This repository has been archived.**

The legacy `databricks/databricks-cli` is deprecated and has been fully replaced by the new Databricks CLI at **https://github.com/databricks/cli**.

We are closing all open issues here as part of archiving this repository. If your issue still affects the new CLI, we'd appreciate you re-opening it at https://github.com/databricks/cli/issues so the team can track and address it there.
