### ISSUE TITLE
Unable to update individual settings when using JobsService.update_job method

### ISSUE THREAD

**Issue by georgikoemdzhiev** [databricks/databricks-cli#606]
Hello, 

Is is possible to add support for updating individual settings with the `update_job` method:
https://github.com/databricks/databricks-cli/blob/fd2ad70d1cbe03b587970a8f41d17004d453707c/databricks_cli/sdk/service.py#L257-L271

Currently, when I would like to update just the `schedule.pause_status` of a job using this code:

```python
from databricks_cli.sdk.api_client import ApiClient
from databricks_cli.sdk.service import JobsService

api_client = ApiClient(host=databricks_host, token=databricks_token)
jobs_service = JobsService(api_client)

reset_dict = {'schedule': {'pause_status': 'PAUSED'}}
jobs_service.update_job(job_id='728701863935760', new_settings=reset_dict)
```

I am getting this error stating that I need to provide the other 2 "required" parameters of the `settings` block:

```log
Traceback (most recent call last):
  File "/home/vsts/work/1/s/main.py", line 34, in <module>
    dr.pause_all_jobs(args.databricks_host, args.databricks_token)
  File "/home/vsts/work/1/s/main.py", line 26, in pause_all_jobs
    jobs_service.update_job(job_id='728701863935760',
  File "/home/vsts/.local/lib/python3.10/site-packages/databricks_cli/sdk/service.py", line 269, in update_job
    return self.client.perform_query(
  File "/home/vsts/.local/lib/python3.10/site-packages/databricks_cli/sdk/api_client.py", line 174, in perform_query
    raise requests.exceptions.HTTPError(message, response=e.response)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://spg-sustainable1-dev.cloud.databricks.com/api/2.0/jobs/update
 Response from server: 
 { 'error_code': 'INVALID_PARAMETER_VALUE',
  'message': 'Missing required fields: '
             'new_settings.schedule.quartz_cron_expression, '
             'new_settings.schedule.timezone_id'}

```
I used databricks-cli==0.17.4 version when I got the above error

**Comment by mroy-seedbox** [comment]
Just read the current job definition from the API (`get_job()`), change the fields you want to change, and post it back. 🤷‍♂️

**Comment by georgikoemdzhiev** [comment]
> Just read the current job definition from the API using `get_job()`, change the fields you want to change, and post it back. 🤷‍♂️

Thank you for your suggestion. I guess that would work as well. However, I am hoping that Databricks can make that process even easier.

**Comment by georgikoemdzhiev** [comment]
> Just read the current job definition from the API using `get_job()`, change the fields you want to change, and post it back. 🤷‍♂️

@mroy-seedbox I tried your suggestion but I am facing another issue. I am getting an `Invalid JSON given in the body of the request - expected a map` error. I have opened another issue to track that #615

**Comment by georgikoemdzhiev** [comment]
> Just read the current job definition from the API using `get_job()`, change the fields you want to change, and post it back. 🤷‍♂️

I tried your suggestion but the approach does not seem to work for me. I tried to change the job's scheduler. I opened another issue to track that here #616

**Comment by chrisst** [comment]
**This repository has been archived.**

The legacy `databricks/databricks-cli` is deprecated and has been fully replaced by the new Databricks CLI at **https://github.com/databricks/cli**.

We are closing all open issues here as part of archiving this repository. If your issue still affects the new CLI, we'd appreciate you re-opening it at https://github.com/databricks/cli/issues so the team can track and address it there.
